x-backend-base: &backend-base
  build:
    context: ./dpachain-api
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  depends_on:
    - dpachain-db2
  environment:
    - PORT=8001
    - MONGO_URI=${MONGO_URI}
  network_mode: host 

services:
  dpachain-db2:
    container_name: dpachain-db2
    env_file:
      - ./dpachain-api/.env2
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27018:27017"
    restart: unless-stopped
    attach: false

  dpachain-api2:
    <<: *backend-base
    container_name: dpachain-api2
    env_file:
      - ./dpachain-api/.env2
    environment:
      - PORT=8001
      - ENV_FILE=.env2
    image: dpachain-api
    restart: unless-stopped

  dpachain-frontend2:
    container_name: dpachain-frontend2
    build:
      context: ./dpachain-frontend
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=3001
      - API_BASE_URL=http://host.docker.internal:8001
    depends_on:
      - dpachain-api2
    restart: unless-stopped
