x-backend-base: &backend-base
  build:
    context: ./dpachain-api
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  depends_on:
    - dpachain-db
  environment:
    - PORT=8000
    - MONGO_URI=${MONGO_URI}
  network_mode: host

services:
  dpachain-db:
    container_name: dpachain-db
    env_file:
      - ./dpachain-api/.env
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    restart: unless-stopped
    attach: false

  dpachain-api:
    <<: *backend-base
    container_name: dpachain-api
    env_file:
      - ./dpachain-api/.env
    environment:
      - PORT=8000
    image: dpachain-api
    restart: unless-stopped

  dpachain-frontend:
    container_name: dpachain-frontend
    build:
      context: ./dpachain-frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=3000
      - API_BASE_URL=http://host.docker.internal:8000
    depends_on:
      - dpachain-api
    restart: unless-stopped
