@startuml
(Zarządzanie listą uczestników) as lista

:Administrator: -> (Dodanie informacji o pracy dyplomowej)
:Administrator: -> (Wyświetlenie listy wszystkich prac dyplomowych)
:Administrator: -> (Wyświetlenie informacji o danej pracy dyplomowej)
:Administrator: -> lista
lista ..> (Dodawanie nowych uczestników) : <<invokes>>
lista ..> (Usuwanie uczestników) : <<invokes>>
lista ..> (Zmiana statusu uczestników) : <<invokes>>
:Administrator: ..> (Utworzenie pierwszego bloku) : <<one-time-only>>
@enduml