@startuml

skin rose
database "MongoDB" {
component [Blockchain Database] as DB
}
package "Backend"{
component [Blockchain service] as BM
component [API]
component [Node service] as NM
component [Peer service] as PM
component [Block service] as BS
}
cloud {
component [Other users in network] as users
}

package "Frontend" {
component [Frontend server] as FS
}


interface IDatabaseConnection
interface IAPIConnection

DB -- IDatabase

BM --( IDatabase
BM -- IDatabaseConnection
BS --( IDatabaseConnection
PM --( IDatabaseConnection

NM <.up.> users : P2P connection

API -> BM
BM <-> BS
BM <-> NM
BM <-> PM

API --( IAPIConnection
FS -- IAPIConnection


@enduml